name: 'Annalise.AI Release Candidate Dispatch Action'
description: 'Annalise.AI Release Candidate Dispatch Action'
inputs:
  token:
    description: 'PAT'
    default: ${{ github.token }}
  doc:
    description: 'Document to dispatch release to'
    required: true
  repo:
    description: 'Title of the service which has been released'
    default: ${{ github.repository }}
  rc:
    description: 'JSON String of required information'
    required: true

runs:
  using: 'node16'
  main: 'index.js'